### ISSUE TITLE
Auth: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by DTFagus** [JeffResc/sharkiq#45]
Hey, 

When I want to authenticate I get the following: 
`Traceback (most recent call last):
  File "/Users/daniel/shark.py", line 7, in <module>
    ayla_api.sign_in()
  File "/opt/homebrew/lib/python3.9/site-packages/sharkiq/ayla_api.py", line 93, in sign_in
    self._set_credentials(resp.status_code, resp.json())
  File "/opt/homebrew/lib/python3.9/site-packages/sharkiq/ayla_api.py", line 82, in _set_credentials
    raise SharkIqAuthError(login_result["error"]["message"])
TypeError: string indices must be integers`

Same for using pything script standalone or the home assistant integration. 
Any thoughts?

If relevant: based in Europe.

**Comment by joshua-pgatour** [comment]
I know this is late, very late... but I had the same issue and if you upgrade to python 3.11 it seems to fix the issue.

**Comment by scottWestveer** [comment]
> I know this is late, very late... but I had the same issue and if you upgrade to python 3.11 it seems to fix the issue.

Seeing this now in the US.. HA GUI shows everything up to date, how do i upgrade Python?

**Comment by tombrant** [comment]
I'm seeing in US as well.  I'm using the correct username and password for the sharkclean.com login.  Is that the right one?  Sometimes I get a 403 error : forbidden now.

Can someone confirm that this is a problem across the board with SharkIq robot integration?

**Comment by funkybunch** [comment]
Likely resolved by #72 - please open a new issue if the issue persists.
